pnconvert = {
    '真': '真',
    '超': '超',
    '檄': '檄',
    '橙': '橙',
    '暁': '暁',
    '晓': '暁',
    '桃': '桃',
    '櫻': '櫻',
    '樱': '櫻',
    '紫': '紫',
    '菫': '菫',
    '堇': '菫',
    '白': '白',
    '雪': '雪',
    '輝': '輝',
    '辉': '輝',
    '舞': '舞',
    '熊': '熊',
    '華': '華',
    '华': '華',
    '爽': '爽',
    '煌': '煌',
    '霸': '霸',
    '覇': '霸',
    '極': '极',
    '极': '极',
    '将': '将',
    '神': '神',
    '者': '者',
    '宙': '宙',
    '星': '星',
    '祭': '祭',
    '祝': '祝',
}

platename_to_file = {
    "真极": "UI_Plate_006101.png",
    "真将": "UI_Plate_006101.5.png",
    "真神": "UI_Plate_006102.png",
    "真舞舞": "UI_Plate_006103.png",
    "超极": "UI_Plate_006104.png",
    "超将": "UI_Plate_006105.png",
    "超神": "UI_Plate_006106.png",
    "超舞舞": "UI_Plate_006107.png",
    "檄极": "UI_Plate_006108.png",
    "檄将": "UI_Plate_006109.png",
    "檄神": "UI_Plate_006110.png",
    "檄舞舞": "UI_Plate_006111.png",
    "橙极": "UI_Plate_006112.png",
    "橙将": "UI_Plate_006113.png",
    "橙神": "UI_Plate_006114.png",
    "橙舞舞": "UI_Plate_006115.png",
    "暁极": "UI_Plate_006116.png",
    "暁将": "UI_Plate_006117.png",
    "暁神": "UI_Plate_006118.png",
    "暁舞舞": "UI_Plate_006119.png",
    "桃极": "UI_Plate_006120.png",
    "桃将": "UI_Plate_006121.png",
    "桃神": "UI_Plate_006122.png",
    "桃舞舞": "UI_Plate_006123.png",
    "櫻极": "UI_Plate_006124.png",
    "櫻将": "UI_Plate_006125.png",
    "櫻神": "UI_Plate_006126.png",
    "櫻舞舞": "UI_Plate_006127.png",
    "紫极": "UI_Plate_006128.png",
    "紫将": "UI_Plate_006129.png",
    "紫神": "UI_Plate_006130.png",
    "紫舞舞": "UI_Plate_006131.png",
    "菫极": "UI_Plate_006132.png",
    "菫将": "UI_Plate_006133.png",
    "菫神": "UI_Plate_006134.png",
    "菫舞舞": "UI_Plate_006135.png",
    "白极": "UI_Plate_006136.png",
    "白将": "UI_Plate_006137.png",
    "白神": "UI_Plate_006138.png",
    "白舞舞": "UI_Plate_006139.png",
    "雪极": "UI_Plate_006140.png",
    "雪将": "UI_Plate_006141.png",
    "雪神": "UI_Plate_006142.png",
    "雪舞舞": "UI_Plate_006143.png",
    "輝极": "UI_Plate_006144.png",
    "輝将": "UI_Plate_006145.png",
    "輝神": "UI_Plate_006146.png",
    "輝舞舞": "UI_Plate_006147.png",
    "霸者": "UI_Plate_006148.png",
    "舞极": "UI_Plate_006149.png",
    "舞将": "UI_Plate_006150.png",
    "舞神": "UI_Plate_006151.png",
    "舞舞舞": "UI_Plate_006152.png",
    "熊极": "UI_Plate_055101.png",
    "熊将": "UI_Plate_055102.png",
    "熊神": "UI_Plate_055103.png",
    "熊舞舞": "UI_Plate_055104.png",
    "華极": "UI_Plate_109101.png",
    "華将": "UI_Plate_109102.png",
    "華神": "UI_Plate_109103.png",
    "華舞舞": "UI_Plate_109104.png",
    "爽极": "UI_Plate_159101.png",
    "爽将": "UI_Plate_159102.png",
    "爽神": "UI_Plate_159103.png",
    "爽舞舞": "UI_Plate_159104.png",
    "煌极": "UI_Plate_209101.png",
    "煌将": "UI_Plate_209102.png",
    "煌神": "UI_Plate_209103.png",
    "煌舞舞": "UI_Plate_209104.png",
    "宙极": "UI_Plate_259101.png",
    "宙将": "UI_Plate_259102.png",
    "宙神": "UI_Plate_259103.png",
    "宙舞舞": "UI_Plate_259104.png",
    "星极": "UI_Plate_309101.png",
    "星将": "UI_Plate_309102.png",
    "星神": "UI_Plate_309103.png",
    "星舞舞": "UI_Plate_309104.png",
    "祭极": "UI_Plate_359101.png",
    "祭将": "UI_Plate_359102.png",
    "祭神": "UI_Plate_359103.png",
    "祭舞舞": "UI_Plate_359104.png",
    "祝极": "UI_Plate_409101.png",
    "祝将": "UI_Plate_409102.png",
    "祝神": "UI_Plate_409103.png",
    "祝舞舞": "UI_Plate_409104.png"
}

level_index_to_file = {
    0: "BSC",
    1: "ADV",
    2: "EXP",
    3: "MST",
    4: "MST_Re"
}

ptv = {
        '真1': 'maimai',
        '真2': 'maimaiPLUS',
        '超': 'GreeN',
        '檄': 'GreeNPLUS',
        '橙': 'ORANGE',
        '暁': 'ORANGEPLUS',
        '晓': 'ORANGEPLUS',
        '桃': 'PiNK',
        '櫻': 'PiNKPLUS',
        '樱': 'PiNKPLUS',
        '紫': 'MURASAKi',
        '菫': 'MURASAKiPLUS',
        '堇': 'MURASAKiPLUS',
        '白': 'MiLK',
        '雪': 'MiLKPLUS',
        '輝': 'FiNALE',
        '辉': 'FiNALE',
        '熊': '舞萌DX',
        '華': '舞萌DX',
        '华': '舞萌DX',
        '爽': '舞萌DX2021',
        '煌': '舞萌DX2021',
        '宙': '舞萌DX2022',
        '星': '舞萌DX2022',
        '祭': '舞萌DX2023',
        '祝': '舞萌DX2023',
        '双': '舞萌DX2024',
        '宴': '舞萌DX2024',
        '镜': '舞萌DX2025'
}

version_list = ["maimai", "maimai PLUS", "maimai GreeN", "maimai GreeN PLUS", "maimai ORANGE", "maimai ORANGE PLUS", "maimai PiNK", "maimai PiNK PLUS", "maimai MURASAKi", "maimai MURASAKi PLUS", "maimai MiLK", 
                "MiLK PLUS", # Fuck
                "maimai FiNALE", "maimai でらっくす", "maimai でらっくす Splash", "maimai でらっくす UNiVERSE", "maimai でらっくす FESTiVAL", "maimai でらっくす BUDDiES", "maimai でらっくす PRiSM"]

cn_version_list = ["maimai", "maimai PLUS", "maimai GreeN", "maimai GreeN PLUS", "maimai ORANGE", "maimai ORANGE PLUS", "maimai PiNK", "maimai PiNK PLUS", "maimai MURASAKi", "maimai MURASAKi PLUS", "maimai MiLK", "maimai MiLK PLUS", "maimai FiNALE", "舞萌DX", "舞萌DX2021", "舞萌DX2022", "舞萌DX2023", "舞萌DX2024", "舞萌DX2025"]

version_abbr_list = ["真1", "真2", "超", "檄", "橙", "晓", "桃", "樱", "紫", "堇", "白", "雪", "辉", "熊华", "爽煌", "宙星", "祭祝", "双宴", "镜"]

version_abbr_str = "真超檄橙晓桃樱紫堇白雪辉熊华爽煌宙星祭祝双宴镜"


version_icon_path = {
    0: "UI_CMN_TabTitle_MaimaiTitle_Ver100.png",
    1: "UI_CMN_TabTitle_MaimaiTitle_Ver110.png",
    2: "UI_CMN_TabTitle_MaimaiTitle_Ver120.png",
    3: "UI_CMN_TabTitle_MaimaiTitle_Ver130.png",
    4: "UI_CMN_TabTitle_MaimaiTitle_Ver140.png",
    5: "UI_CMN_TabTitle_MaimaiTitle_Ver150.png",
    6: "UI_CMN_TabTitle_MaimaiTitle_Ver160.png",
    7: "UI_CMN_TabTitle_MaimaiTitle_Ver170.png",
    8: "UI_CMN_TabTitle_MaimaiTitle_Ver180.png",
    9: "UI_CMN_TabTitle_MaimaiTitle_Ver185.png",
    10: "UI_CMN_TabTitle_MaimaiTitle_Ver190.png",
    11: "UI_CMN_TabTitle_MaimaiTitle_Ver195.png",
    12: "UI_CMN_TabTitle_MaimaiTitle_Ver199.png",
    13: "UI_CMN_TabTitle_MaimaiTitle_Ver200.png",
    14: "UI_CMN_TabTitle_MaimaiTitle_Ver214.png",
    15: "UI_CMN_TabTitle_MaimaiTitle_Ver220.png",
    16: "UI_CMN_TabTitle_MaimaiTitle_Ver230.png",
    17: "UI_CMN_TabTitle_MaimaiTitle_Ver240.png",
    18: "UI_CMN_TabTitle_MaimaiTitle_Ver250.png"
}

genre_icon_path = {
    "舞萌": "UI_CMN_TabTitle_Original.png",
    "流行&动漫": "UI_CMN_TabTitle_PopsAnime.png",
    "其他游戏": "UI_CMN_TabTitle_Variety.png",
    "niconico & VOCALOID": "UI_CMN_TabTitle_Niconico.png",
    "东方Project": "UI_CMN_TabTitle_Toho.png",
    "音击&中二节奏": "UI_CMN_TabTitle_Chugeki.png",
    "maimai": "UI_CMN_TabTitle_Original.png",
    "POPSアニメ": "UI_CMN_TabTitle_PopsAnime.png",
    "ゲームバラエティ": "UI_CMN_TabTitle_Variety.png",
    "niconicoボーカロイド": "UI_CMN_TabTitle_Niconico.png",
    "東方Project": "UI_CMN_TabTitle_Toho.png",
    "オンゲキCHUNITHM": "UI_CMN_TabTitle_Chugeki.png",
    "宴会場": "UI_CMN_TabTitle_Utage.png"
}

info_to_file_dict = {
    "sssp": "SSSp",
    "sss": "SSS",
    "ssp": "SSp",
    "ss": "SS",
    "sp": "Sp",
    "s": "S",
    "aaa": "AAA",
    "aa": "AA",
    "a": "A",
    "bbb": "BBB",
    "bb": "BB",
    "b": "B",
    "c": "C",
    "d": "D",
    "fc": "FC",
    "fcp": "FCp",
    "ap": "AP",
    "app": "APp",
    "sync": "SP",
    "fs": "FS",
    "fsp": "FSp",
    "fsd": "FSD",
    "fsdp": "FSDp",
    "fdx": "FSD",
    "fdxp": "FSDp"
}

SCORE_COEFFICIENT_TABLE = [
    [0, 0, 'd'],
    [50, 8, 'c'],
    [60, 9.6, 'b'],
    [70, 11.2, 'bb'],
    [75, 12.0, 'bbb'],
    [80, 13.6, 'a'],
    [90, 15.2, 'aa'],
    [94, 16.8, 'aaa'],
    [97, 20, 's'],
    [98, 20.3, 'sp'],
    [99, 20.8, 'ss'],
    [99.5, 21.1, 'ssp'],
    #[99.9999, 21.4, 'ssp'],
    [100, 21.6, 'sss'],
    #[100.4999, 22.2, 'sss'],
    [100.5, 22.4, 'sssp']
]

SCORE_COEFFICIENT_TABLE_LEGANCY = [
    [0, 0, 'd'],
    [50, 5.0, 'c'],
    [60, 6.0, 'b'],
    [70, 7.0, 'bb'],
    [75, 7.5, 'bbb'],
    [80, 8.5, 'a'],
    [90, 9.5, 'aa'],
    [94, 10.5, 'aaa'],
    [97, 12.5, 's'],
    [98, 12.7, 'sp'],
    [99, 13.0, 'ss'],
    [99.5, 13.2, 'ssp'],
    [100, 13.5, 'sss'],
    [100.5, 14.0, 'sssp']
]

rank_list_lower = ["d", "c", "b", "bb", "bbb", "a", "aa", "aaa", "s", "sp", "ss", "ssp", "sss", "sssp"]
rank_list_upper = ["D", "C", "B", "BB", "BBB", "A", "AA", "AAA", "S", "Sp", "SS", "SSp", "SSS", "SSSp"]
fc_list_lower = ["", "fc", "fcp", "ap", "app"]
fc_list_upper = ["", "FC", "FCp", "AP", "APp"]
fs_list_lower = ["", "sync", "fs", "fsp", "fsd", "fsdp"]
fs_list_upper = ["", "SP", "FS", "FSp", "FSD", "FSDp"]
level_list = ["1", "2", "3", "4", "5", "6", "7", "7+", "8", "8+", "9", "9+", "10", "10+", "11", "11+", "12", "12+", "13", "13+", "14", "14+", "15"]